# Generated by Django 6.0 on 2025-12-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='contact_info',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
