# Generated by Django 6.0 on 2025-12-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_testimonial_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
