# Generated by Django 6.0 on 2025-12-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
