# Generated by Django 6.0 on 2025-12-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_photos/'),
        ),
    ]
